apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-ms-config
  namespace: retail-microservices-dev
data:
  APP_FRONTEND_BASE_URL: "https://retail-novamart.netlify.app"
  APP_CORS_ALLOWED_ORIGINS: "https://retail-novamart.netlify.app"
  APP_MAIL_FROM: "NovaMart <onboarding@resend.dev>"
  EUREKA_HOST: "discovery.retail-microservices-dev.svc.cluster.local"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "retail-ms-kafka.retail-microservices-dev.svc.cluster.local:9092"
  SPRING_DATA_REDIS_HOST: "retail-ms-redis.retail-microservices-dev.svc.cluster.local"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_CACHE_TYPE: "redis"
  PRODUCT_SERVICE_URL: "http://product-service.retail-microservices-dev.svc.cluster.local:8084"
  PAYMENT_SERVICE_URL: "http://payment-service.retail-microservices-dev.svc.cluster.local:8082"
  ORDER_SERVICE_URL: "http://order-service.retail-microservices-dev.svc.cluster.local:8085"
  CUSTOMER_SERVICE_HOST: "customer-service.retail-microservices-dev.svc.cluster.local"
