apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
  namespace: retail-microservices-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: retail-microservices-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: order-db
          image: postgres:14-alpine
          env:
            - name: POSTGRES_DB
              value: order_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: retail-ms-secrets
                  key: ORDER_DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retail-ms-secrets
                  key: ORDER_DB_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: order-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER -d order_db"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: order-db-storage
          persistentVolumeClaim:
            claimName: order-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: retail-microservices-dev
spec:
  selector:
    app: order-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
