apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: retail-microservices-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: suissitakwa/retail-ms-api-gateway:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: retail-ms-config
                  key: EUREKA_HOST
            - name: APP_CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: retail-ms-config
                  key: APP_CORS_ALLOWED_ORIGINS
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8090
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8090
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: retail-microservices-dev
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8090
      targetPort: 8090
  type: ClusterIP
