apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: retail-microservices-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: suissitakwa/retail-ms-config-server:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: retail-microservices-dev
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP
