apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  namespace: retail-microservices-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - name: discovery
          image: suissitakwa/retail-ms-discovery:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8761
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8761
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: retail-microservices-dev
spec:
  selector:
    app: discovery
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
