apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: retail-microservices-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: suissitakwa/retail-ms-product-service:dev-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: retail-ms-config
                  key: EUREKA_HOST
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://product-db:5432/product_db"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: retail-ms-secrets
                  key: PRODUCT_DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retail-ms-secrets
                  key: PRODUCT_DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: retail-ms-secrets
                  key: JWT_SECRET_KEY
            - name: SPRING_CACHE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: retail-ms-config
                  key: SPRING_CACHE_TYPE
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: retail-ms-config
                  key: SPRING_DATA_REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: retail-ms-config
                  key: SPRING_DATA_REDIS_PORT
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: retail-microservices-dev
spec:
  selector:
    app: product-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
